name: CI - Build and Push Docker Image

# КОГДА запускать робота?
on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**' # Запускать, только если изменились файлы внутри папки app/
                 # (Если ты поменял README или Ansible, пересобирать Докер не нужно)

# ЧТО делать?
jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Робот берет виртуальную машину на Ubuntu (в облаке Microsoft)
    
    steps:
      # 1. Скачать твой код из репозитория
      - name: Check out the repo
        uses: actions/checkout@v3

      # 2. Залогиниться в Docker Hub (используя ключи из сейфа)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Собрать образ и отправить (Push)
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./app           # ГДЕ лежит Dockerfile (у нас в папке app)
          push: true               # Отправлять ли в облако? ДА.
          # Ставим два тега: v1 (фиксированный) и latest (всегда свежий)
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/my-ai-service:v1
            ${{ secrets.DOCKER_USERNAME }}/my-ai-service:latest
